<a href="https://colab.research.google.com/github/uditi-12/ML_project/blob/main/ML_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [119]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [120]:
import numpy as np
import pandas as pd
df_train = pd.read_csv(('/content/drive/MyDrive/VIT/Sem_5(1)/B-ML (1)/LABS/dataset/train_MachineLearningCVE.csv'), skipinitialspace=True, nrows = 10000)
df_test = pd.read_csv(('/content/drive/MyDrive/VIT/Sem_5(1)/B-ML (1)/LABS/dataset/test_MachineLearningCVE.csv'), skipinitialspace=True, nrows = 10000)

In [121]:
#df_test.Label.unique()

In [122]:
#df_train.Label.unique()

In [123]:
df = pd.concat([df_train, df_test], axis=0, copy=True)
df.Label.unique()

array([ 0, 10,  4,  7,  3,  5,  6, 11,  1, 12, 14])

In [124]:
#df.head

In [125]:
df=df.dropna()

In [126]:
#df.dtypes

In [127]:
#df['Label'].value_counts(sort=True)

In [128]:
df = df.sample(frac=1)
x = df.iloc[:, df.columns != 'Label']
y = df[['Label']].to_numpy()

In [129]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(x)

In [130]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=1, stratify=y)

In [131]:
from imblearn.over_sampling import SMOTE 
k=2
sm = SMOTE(k_neighbors=k, random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train.ravel()) 

In [132]:
X_train.shape

(18000, 78)

In [133]:
X_train

Destination Port  Flow Duration  Total Fwd Packets  \
1191               443      5735211.0                  9   
8516                53        50299.0                  2   
5975                53        26691.0                  2   
8257               443    115409745.0                 44   
6007                53        48366.0                  1   
...                ...            ...                ...   
1493                80     99765580.0                  7   
8519               443    113153586.0                 40   
3302                53          169.0                  2   
3988               443       136364.0                 14   
4873             52188            1.0                  2   

      Total Backward Packets  Total Length of Fwd Packets  \
1191                       6                          350   
8516                       2                           64   
5975                       2                           68   
8257                      57                          743   
6007                       1                           55   
...                      ...                          ...   
1493                       6                          368   
8519                      44                         1628   
3302                       2                           94   
3988                      10                          847   
4873                       0                           12   

      Total Length of Bwd Packets  Fwd Packet Length Max  \
1191                         4867                    193   
8516                          204                     32   
5975                          158                     34   
8257                        76082                    354   
6007                           93                     55   
...                           ...                    ...   
1493                        11595                    368   
8519                        47059                    336   
3302                          206                     47   
3988                         8831                    373   
4873                            0                      6   

      Fwd Packet Length Min  Fwd Packet Length Mean  Fwd Packet Length Std  \
1191                      0               38.888889              71.129186   
8516                     32               32.000000               0.000000   
5975                     34               34.000000               0.000000   
8257                      0               16.886364              64.409741   
6007                     55               55.000000               0.000000   
...                     ...                     ...                    ...   
1493                      0               52.571429             139.090926   
8519                      0               40.700000             103.236398   
3302                     47               47.000000               0.000000   
3988                      0               60.500000             116.258829   
4873                      6                6.000000               0.000000   

      ...  act_data_pkt_fwd  min_seg_size_forward   Active Mean   Active Std  \
1191  ...                 3                  32.0  155518.00000       0.0000   
8516  ...                 1                  20.0       0.00000       0.0000   
5975  ...                 1                  32.0       0.00000       0.0000   
8257  ...                 4                  32.0   42871.27273   35355.2571   
6007  ...                 0                  20.0       0.00000       0.0000   
...   ...               ...                   ...           ...          ...   
1493  ...                 1                  32.0     379.00000       0.0000   
8519  ...                 6                  32.0  268192.09090  736552.1540   
3302  ...                 1                  20.0       0.00000       0.0000   
3988  ...                 6                  32.0       0.00000       0.0000   
4873  ...     

In [134]:
y_train_1 = y_train[:3000]
y_train_1

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [135]:
X_train_1 = X_train.iloc[:3000]
X_train_2 = X_train.iloc[3000:6000]
X_train_3 = X_train.iloc[6000:]
y_train_1 = y_train[:3000]
y_train_2 = y_train[3000:6000]
y_train_3 = y_train[6000:]

In [136]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=2)
kf.get_n_splits(X)
print(kf)
KFold(n_splits=2, random_state=None, shuffle=False)
for train_index, test_index in kf.split(X):
  print("TRAIN:", train_index, "TEST:", test_index)
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]

KFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [10000 10001 10002 ... 19997 19998 19999] TEST: [   0    1    2 ... 9997 9998 9999]
TRAIN: [   0    1    2 ... 9997 9998 9999] TEST: [10000 10001 10002 ... 19997 19998 19999]


In [137]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)

y_train_1=y_train_1.ravel();
# fitting the model for grid search
grid.fit(X_train_1, y_train_1)

Fitting 5 folds for each of 25 candidates, totalling 125 fits


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  UserWarning,


[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.852 total time=   2.1s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.853 total time=   2.5s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.853 total time=   3.4s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.852 total time=   3.7s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.850 total time=   3.6s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.852 total time=   3.8s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.853 total time=   3.6s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.853 total time=   2.1s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.852 total time=   2.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.850 total time=   2.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.852 total time=   2.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.853 total time=   2.0s
[CV 3/5] END .....C=0.1, gam

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [138]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
grid_vals = {'penalty': ['l1','l2'], 'C': [0.001,0.01,0.1,1]}
grid_lr = GridSearchCV(estimator=model, param_grid=grid_vals, 
scoring='accuracy', cv=6, refit=True, return_train_score=True) 
#Training and Prediction
grid_lr.fit(X_train, y_train)
preds = grid_lr.best_estimator_.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=6.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist

In [139]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=4, n_informative=2, n_redundant=0, random_state=0, shuffle=False)
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X, y)

RandomForestClassifier(max_depth=2, random_state=0)

In [140]:
from sklearn.neural_network import MLPClassifier
from sklearn.svm import NuSVC
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.ensemble import RandomForestClassifier
from mlxtend.classifier import StackingCVClassifier
import numpy as np
#Initializing Support Vector classifier
classifier1 = SVC(C = 50, degree = 1, gamma = "auto", kernel = "rbf", probability = True)
# Initializing Multi-layer perceptron classifier
classifier2 = MLPClassifier(activation = "relu", alpha = 0.1, hidden_layer_sizes = (10,10,10), learning_rate = "constant", max_iter = 2000, random_state = 1000)
# Initialing Nu Support Vector classifier
classifier3 = NuSVC(degree = 1, kernel = "rbf", nu = 0.25, probability = True)
# Initializing Random Forest classifier
classifier4 = RandomForestClassifier(n_estimators = 500, criterion = "gini", max_depth = 10,max_features = "auto", min_samples_leaf = 0.005,
min_samples_split = 0.005, n_jobs = -1, random_state = 1000)
# Initializing the StackingCV classifier
sclf = StackingCVClassifier(classifiers = [classifier1, classifier2, classifier3, classifier4],shuffle = False,use_probas = True,cv = 5,meta_classifier = SVC(probability = True))


ImportError: ignored

In [145]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import StackingClassifier
estimators = [
('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
('svr', make_pipeline(StandardScaler(),
LinearSVC(random_state=42)))
]
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [148]:
from sklearn import metrics
#Instantiate and fit the RandomForestClassifier
forest = RandomForestClassifier()
forest.fit(X_train, y_train)
# Make predictions for the test set
y_pred_test = forest.predict(X_test)
# View confusion matrix for test data and predictions
metrics.confusion_matrix(y_test, y_pred_test)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[8507,    0,    0,    1,    5,    0,    0,    3,    0,    0,    0],
       [  10,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   3,    0,   47,    0,    0,    0,    0,    0,    0,    0,    0],
       [   4,    0,    0,  968,    0,    0,    0,    0,    0,    0,    0],
       [   4,    0,    0,    0,   15,    1,    0,    0,    0,    0,    0],
       [   2,    0,    0,    0,    2,   20,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   27,    0,    0,    0,    0],
       [   1,    0,    0,    0,    0,    0,    0,  346,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,   26,    0,    0],
       [   3,    0,    0,    0,    0,    0,    0,    0,    0,    4,    0],
       [   1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [149]:
from sklearn.tree import DecisionTreeClassifier
clf_en = DecisionTreeClassifier(criterion='entropy',max_depth=3, 
random_state=0)
clf_en.fit(X_train, y_train)
y_pred_en = clf_en.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_en)
print('Confusion matrix\n\n', cm)

Confusion matrix

 [[8347    0    1   10    0    0    0  158    0    0    0]
 [   8    0    0    0    0    0    0    2    0    0    0]
 [  16    0   34    0    0    0    0    0    0    0    0]
 [ 307    0    0  665    0    0    0    0    0    0    0]
 [  20    0    0    0    0    0    0    0    0    0    0]
 [  24    0    0    0    0    0    0    0    0    0    0]
 [  27    0    0    0    0    0    0    0    0    0    0]
 [   2    0    0    0    0    0    0  345    0    0    0]
 [  26    0    0    0    0    0    0    0    0    0    0]
 [   7    0    0    0    0    0    0    0    0    0    0]
 [   1    0    0    0    0    0    0    0    0    0    0]]


In [150]:
from sklearn.metrics import accuracy_score
import xgboost as xgb
# Init classifier
xgb_cl = xgb.XGBClassifier()
# Fit
xgb_cl.fit(X_train, y_train)
# Predict
preds = xgb_cl.predict(X_test)
# Score
accuracy_score(y_test, preds)


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9969

In [157]:
# generate data
trainX, trainy, testX, testy = X_train,y_train,X_test,y_test
# fit model
model = model.fit(trainX, trainy)

# predict probabilities for test set
yhat_probs = model.predict(testX)#, verbose=0)
# predict crisp classes for test set
yhat_classes = model.predict_classes(testX)#, verbose=0)

# reduce to 1d array
yhat_probs = yhat_probs[:, 0]
yhat_classes = yhat_classes[:, 0]
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
# precision tp / (tp + fp)
precision = precision_score(testy, yhat_classes)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(testy, yhat_classes)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(testy, yhat_classes)
print('F1 score: %f' % f1)
# ROC AUC
auc = roc_auc_score(testy, yhat_probs)
print('ROC AUC: %f' % auc)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


AttributeError: ignored

In [158]:
import shap
# Generate the Tree explainer and SHAP values
explainer = shap.TreeExplainer(xgb_mod)
shap_values = explainer.shap_values(X)
expected_value = explainer.expected_value
# Generate summary bar plot 
shap.summary_plot(shap_values, X,plot_type="bar") 
# Generate dependence plot
shap.dependence_plot("worst concave points", shap_values, X, interaction_index="mean concave points")

ModuleNotFoundError: ignored